### ISSUE TITLE
Your Approach vs Blueprints

### ISSUE THREAD

**Issue by jamesdixon** [huafu/ember-data-sails#16]
Hi,

Not a bug, but just a quick question regarding your approach versus overriding blueprints. Seems like this may be easier to maintain long-term rather than overriding blueprints. Can you provide any insight?

Best,
James

**Comment by huafu** [comment]
Hey @jamesdixon, I am sorry to answer that late but I am very busy with 2 projects lately and kinda have no time badly :-(

I think one or another approach is up to you. While i like the blueprints since they provide a better way to side load records without having duplicates or deep nested models, without my socket service and adapter in another hand you can't use the sockets to communicate with Sails. Combining both is a good solution of you plan on using sockets and have a json friendly with ember data rest adapter which, I think, is the best way of serializable data.

I hope this answered your questions.
